

#ifndef ZXPLAYER_STATAUS_H
#define ZXPLAYER_STATAUS_H

#endif //ZXPLAYER_STATAUS_H

#define ZXPLAYER_THREAD_MAIN 1
#define ZXPLAYER_THREAD_CHILD 2

#define FFMPEG_CAN_NOT_OPEN_URL 3
#define FFMPEG_CAN_NOT_FIND_STREAMS 4

#define ZXPLAYER_CODEC_FAILD 5


